### PR TITLE
Bump flog version

### PR DESCRIPTION
**Pull request by noelia-lencina**
The intent of this PR is to generate a new docker image build with the latest flog version.

### CODE REVIEW

**Comment by ale7714** [comment]
@zenspider Hi Ryan, Ale from Code Climate here. I hope you're well. @noelia-lencina is an engineer from our team. Would it be possible to give us write access so we can update the flog plugin? thank you!

**Comment by zenspider** [comment]
Totally... but... didn't I transfer this project over to y'all ages ago? I thought Max & I went and did that already. Happy to do so if it didn't take or I'm misremembering which one it was.

**Comment by zenspider** [comment]
Sorry... @maxjacobson ^^^

**Comment by zenspider** [comment]
@efueger also is a collaborator, and Gordon still has a years old pending invite.

Wanna just take the project? It's not like I'm doing anything with it.

**Comment by zenspider** [comment]
OK. I joined the @codeclimate-community org, transferred this project there, and added staff. @ale7714 and @efueger... you should have full admin access?

**Comment by ale7714** [comment]
@zenspider thank you so much! yes we're good to go! hope you're safe and healthy.

**Pull request merged**
